version: "3.9"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pythongym-backend
      - pythongym-frontend
    ports:
      - 7800:7800

  pythongym-backend:
    build: backend
    image: pythongym-backend
    restart: "no"
    volumes:
      - ./backend/:/app
      - ./app-cache/:/app-cache
    expose:
      - "7777-7778:7777"
    depends_on:
      - database
      - flyway
      - grader-api
    env_file:
      - project.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"


  pythongym-frontend:
    build: frontend
    image: pythongym-frontend
    restart: "no"
    volumes:
      - ./frontend/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - pythongym-backend

  grader-api:
    build: grader-api
    image: grader-api
    restart: "no"
    volumes:
      - ./grader-api/:/app
      - ./app-cache/:/app-cache
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000

  database:
    container_name: database-server-dab-p1-8c8e4482-eac9-449f-830f-7f9a97bb7a53
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:10.8.1
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests